### ISSUE TITLE
Code reproduction issues

### ISSUE THREAD

**Issue by WangXuCh** [xingy038/DS-Depth#1]
Hello, I encountered some errors while reproducing your code as follows:
`No CUDA GPUs are available`
And there were errors importing modules from `. py` files. Many imports were `from manydepth`, but I think you should change it to ` from dsdepth`, so can you upload a complete, bug free code?
Actually, I can reproduce many depths, but replicating your code will result in No CUDA GPUs.
Looking forward to your reply!

**Comment by xingy038** [comment]
Hi,

Sorry about that, I've fixed the code. 

For `No CUDA GPUs are available`, you can try to set  `os.environ["CUDA_VISIBLE_DEVICES"]="0"`. OR please double-check your pytorch version.

Also, it has been almost a year since this code was completed, so I'm sorry I can't answer you in detail.

**Comment by WangXuCh** [comment]
> Hi,
> 
> Sorry about that, I've fixed the code.
> 
> For `No CUDA GPUs are available`, you can try to set `os.environ["CUDA_VISIBLE_DEVICES"]="0"`. OR please double-check your pytorch version.
> 
> Also, it has been almost a year since this code was completed, so I'm sorry I can't answer you in detail.

Thank you for your reply. The code is now working! Best wishes!
